In [1]:
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor
import xgboost as xgb
import seaborn as sns
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

# Make NumPy printouts easier to read.
np.set_printoptions(precision=3, suppress=True)

## Read CSV
data_source = "./data/vehicle_data_v2.csv"
df = pd.read_csv(data_source)

print(f'Data ingested -- Found {len(df)} Rows')

/Users/andyczeropski/opt/miniconda3/envs/bat/lib/python3.10/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index

Data ingested -- Found 87583 Rows

In [2]:
'''
Steps to clean data
1. Remove vehicles that did not sell - 'sold' == False
2. Consolidate engine sizes for models
    - will need to impute values for some vehicles that show 0
    - electric vehicles will show 0 as they do not have cylinders
3. remove url column
4. Check year column for any dates > 2022
5. Check mileage for outliers

'''

# print(df.nunique())

# We have a total of 52 nans, so we drop them
# data.dropna(inplace=True)
# print(df.isna().sum())

# print(df.describe().transpose())

"\nSteps to clean data\n1. Remove vehicles that did not sell - 'sold' == False\n2. Consolidate engine sizes for models\n    - will need to impute values for some vehicles that show 0\n    - electric vehicles will show 0 as they do not have cylinders\n3. remove url column\n4. Check year column for any dates > 2022\n5. Check mileage for outliers\n\n"

In [3]:
# Drop unneeded columns from df, these are used for the front end
for col in ['url', 'live']:
    if col in df.columns:
        df.drop([col], axis=1, inplace=True)
        
# Get rid of BAD URL rows
df = df[df.make != "BAD"]

# Drop sold column
if 'sold' in df.columns:
    # Drop any auctions where the vehicle didn't sell, as the price for these was not good enough
    print(f'Removed {len(df[df.sold == False])} vehicles that did not sell')
    df = df[df.sold == True]
    df.drop(['sold'], axis=1, inplace=True)
    
df = df.reset_index(drop=True)
df

Removed 19365 vehicles that did not sell

,auction_year,make,model,model2,model_desc,year,miles,color,engine_size,cylinders,bid_price
0,2022,acoma,era1970s,era1970s,mini comtesse,1975,745.0,white,0.0,2.0,10100
1,2020,acoma,era1970s,era1970s,mini comtesse,1975,745.0,white,0.0,2.0,8000
2,2022,acura,integra,integra,gs-r,1997,52000.0,green,1.8,4.0,26500
3,2022,acura,integra,integra,special edition sedan,1995,72000.0,black,1.8,4.0,7100
4,2022,acura,integra,integra,special edition coupe,1995,43000.0,white,1.8,4.0,8900
...,...,...,...,...,...,...,...,...,...,...,...
68136,2022,yamaha,era1970s,era1970s,dt125 enduro,1975,2500.0,white,0.0,2.0,4100
68137,2022,yamaha,era1980s,era1980s,xj650 seca turbo,1982,12000.0,blue,0.0,4.0,3100
68138,2022,yamaha,era1970s,era1970s,dt125 enduro,1975,1200.0,white,0.0,2.0,5900
68139,2022,yamaha,era2000s,era2000s,yzf-r1,2000,6000.0,black,0.0,4.0,12750
68140,2022,zimmer,era1980s,era1980s,golden spirit,1982,5500.0,brown,0.0,8.0,16000

### Impute Year Outliers to Model Mean

In [4]:
# Get list of columns that have nan's so we can loop through them
nan_lst = df.isna().sum()
nan_columns = []
for column in df.columns:
    if nan_lst[column] > 0:
        nan_columns.append(column)

print(nan_columns)

model_mean_dict = dict()

# create dict for model mean/mode for nan columns
for column in nan_columns:
    # Check if column contains numerical values - using random 42 locator
    try: # numeric variable
        model_mean_dict[column] = round(df[column].mean(), 2)
    except:
        model_mean_dict[column] = df[column].mode()[0]

# Loop through dataframe and impute all nans - note this can take a bit of time to compute
for idx in range(len(df)):
    row = df.iloc[idx]
    for nan_col_name in nan_columns:
        col = row[nan_col_name]
        if col != col:
            # print(idx, row.make)
            if nan_col_name == 'model_desc':
                df.at[idx, 'model_desc'] = row.model
            else:
                try:
                    try: # numeric variable
                        model_col_avg = round(df[df.model == row.model][nan_col_name].mean(), 2)
                    except: # cetegorical variable
                        model_col_avg = df[df.model == row.model][nan_col_name].mode()[0]
                        
                    df.at[idx, nan_col_name] = model_col_avg
                    
                except:
                    df_col_avg = model_mean_dict.get(nan_col_name)
                    df.at[idx, nan_col_name] = df_col_avg

print(df.isna().sum())

['model_desc', 'miles', 'color', 'cylinders']
auction_year    0
make            0
model           0
model2          0
model_desc      0
year            0
miles           0
color           2
engine_size     0
cylinders       0
bid_price       0
dtype: int64

### Impute Year outliers

In [5]:
print(len(df[df.year > 2022]))

# Impute all outlier model years to average year per model - but if average is > 2022, set to 2000
for idx in range(len(df)):
    row = df.iloc[idx]
    year = row.year
    model = row.model
    # avg_year = row[row.model == model].year.mean()
    if year > 2022:
        model_year_avg = np.floor(df[df.model == model].year.mean())
        if model_year_avg < 2022:
            df.at[idx, 'year'] = model_year_avg
        else:
            df.at[idx, 'year'] = 2000
            
print(len(df[df.year > 2022]))

81
0

### Impute Mileage Outliers

In [6]:
print(len(df[df['miles'] > 500000]))
# print(df[df['miles'] > 500000].head(20))

# Impute all outlier model years to average year per model - but if average is > 2022, set to 2000
for idx in range(len(df)):
    row = df.iloc[idx]
    miles = row.miles
    model = row.model
    # avg_year = row[row.model == model].year.mean()
    if miles > 500000:
        model_miles_avg = np.floor(df[df.model == model].miles.mean())
        if model_miles_avg < 500000:
            df.at[idx, 'miles'] = model_miles_avg
        else:
            df.at[idx, 'miles'] = 150000
            
print(len(df[df['miles'] > 500000]))

79
0

## Impute Engine Size to Model Mean

In [7]:
# Code here

### Impute NAN's to Model Mean

In [8]:
# Drop any leftover nans - cursory check, shouldn't be any nans left
df = df.dropna()

# Replace any pesky pd.NA with None - if not this will cause error when fitting model
df.replace(to_replace=pd.NA, value=None, inplace=True)
print("Number of unique Makes:", df.make.nunique())

# Check nan values again
print('\nAfter:\n', df.isna().sum())

Number of unique Makes: 223

After:
 auction_year    0
make            0
model           0
model2          0
model_desc      0
year            0
miles           0
color           0
engine_size     0
cylinders       0
bid_price       0
dtype: int64

/var/folders/zc/257ljhc92snb384hphnpxgqc0000gn/T/ipykernel_31797/2226255121.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace(to_replace=pd.NA, value=None, inplace=True)

In [9]:
# sns.pairplot(df[['auction_year', 'year', 'miles', 'cylinders', 'bid_price']], diag_kind='kde')

In [10]:
# sns.heatmap(df.corr(), annot = True)

In [11]:
# Allows for Mustang vs Shelby Mustang price differences
df.loc[df.model == 'shelby mustang', 'model2'] = 'shelby mustang'

df[df.model == 'shelby mustang']

,auction_year,make,model,model2,model_desc,year,miles,color,engine_size,cylinders,bid_price
23567,2022,ford,shelby mustang,shelby mustang,mustang gt-h,2006,17000.0,w/gold,4.6,8.0,33000
23570,2022,ford,shelby mustang,shelby mustang,mustang gt350 convertible 6-speed,2012,3700.0,w/gold,5.0,8.0,78000
23575,2022,ford,shelby mustang,shelby mustang,mustang gt 5-speed,2007,29000.0,w/silver,4.6,8.0,22500
23581,2022,ford,shelby mustang,shelby mustang,mustang gt-c 5-speed,2008,1100.0,w/silver,4.6,8.0,37949
23598,2022,ford,shelby mustang,shelby mustang,mustang gt500 coupe,2007,3500.0,w/white,5.4,8.0,48250
...,...,...,...,...,...,...,...,...,...,...,...
63278,2022,ford,shelby mustang,shelby mustang,mustang super snake coupe,2020,6000.0,w/black,5.0,8.0,89550
63280,2022,ford,shelby mustang,shelby mustang,mustang gt500 heritage edition,2022,21.0,blue,5.2,8.0,122000
63282,2022,ford,shelby mustang,shelby mustang,mustang gt500 carbon fiber track pack,2021,425.0,w/black,5.2,8.0,96000
63284,2022,ford,shelby mustang,shelby mustang,mustang gt500,2021,1600.0,blue,5.2,8.0,80400
63289,2022,ford,shelby mustang,shelby mustang,mustang gt500 heritage edition,2022,6.0,blue,5.2,8.0,142000

### Start Training

In [12]:
# name value to predict
target_feature = "bid_price"

y = df[target_feature]
X = df.drop(target_feature, axis=1)
print(len(X) == len(y))

True

In [13]:
## Find Numerical & Categorical Columns
# Get numerical and categorical feature columns
print('\nCalculating Numerical and Categorical Features...')
print(f'There are {len(X.columns)} total columns.')

numerical_features = X.select_dtypes(include='number').columns.tolist()
print(f'There are {len(numerical_features)} numerical features.')

categorical_features = X.select_dtypes(exclude='number').columns.tolist()
print(f'There are {len(categorical_features)} categorical features.', '\n')

print(X.columns)

## Pre-Process Data

print('Fetching Preprocessing Pipeline...\n')

numeric_pipeline = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='mean', missing_values=np.nan)),
    ('scale', MinMaxScaler())
])

categorical_pipeline = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='most_frequent', missing_values=np.nan)),
    ('one-hot', OneHotEncoder(handle_unknown='ignore', sparse=False))
])

full_processor = ColumnTransformer(transformers=[
    ('number', numeric_pipeline, numerical_features),
    ('category', categorical_pipeline, categorical_features)
])


# model = XGBRegressor(n_estimators=100, random_state=42)

# model_pipeline = Pipeline(steps=[
#         ('preprocessor', full_processor),
#         ('model', model)
#     ])

Calculating Numerical and Categorical Features...
There are 10 total columns.
There are 5 numerical features.
There are 5 categorical features.

Index(['auction_year', 'make', 'model', 'model2', 'model_desc', 'year',
       'miles', 'color', 'engine_size', 'cylinders'],
      dtype='object')
Fetching Preprocessing Pipeline...

In [14]:
model = XGBRegressor(random_state=42, learning_rate=0.5, n_estimators=400, max_depth=5)


model_pipeline = Pipeline(steps=[
        ('preprocessor', full_processor),
        ('model', model)
    ])

# For initial training
# X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.20, random_state=42)
# hist = model_pipeline.fit(X_train, y_train)

# For final training to train on all data
hist = model_pipeline.fit(X, y)

In [16]:
# Preprocessing of validation data, get predictions
preds = model_pipeline.predict(X)

# Evaluate the model
MAE = mean_absolute_error(y, preds)
r2 = model_pipeline.score(X, y)

print('MAE:', MAE)
print('R2:', r2)

# preds

MAE: 9791.830237372418
R2: 0.9217366330618152

## Testing Model Predictions

In [29]:
mustang_gt = [2022, "ford", "mustang s550", 'mustang s550', 'gt 6-speed', 2018, 3100, "white", 5.0, 8]
mustang_gt350r = [2022, "ford", "shelby mustang", 'mustang s550', 'shelby gt350r', 2018, 3100, "blue", 5.2, 8]
mustang_gt350 = [2022, "ford", "shelby mustang", 'mustang s550', 'shelby gt350', 2018, 3100, "blue", 5.2, 8]
sti = [2022, "subaru", "wrx sti", "wrx sti", 'impreza sti', 2005, 35000, "blue", 2.5, 4]
ford_gt = [2022, "ford", "gt 1st generation", "gt 1st generation", 'gt 1st generation', 2005, 7000, "red", 5.4, 8]
ferrari_308 = [2022, "ferrari", "308", "308", 'gtb', 1978, 23000, "silver", 2.9, 8]
landcruiser = [2022, "toyota", "land cruiser fj45", "land cruiser fj45", 'cruiser fj45', 1984, 60000, "white", 4.2, 6]
aston_martin = [2022, "aston martin", "db9", "db9", 'martin coupe', 2005, 22000, "green", 6, 12]
ferrari_250 = [2022, "ferrari", "250 gt", "250 gt", '250 gte 2+2 series ii', 1962, 51000, "red", 3.0, 12]
bmw_m3 = [2022, "bmw", "e90/e92/e93 m3", "e90/e92/e93 m3", 'm3 coupe 6-speed', 2011, 39000, "blue", 4.0, 8]

model_list = [mustang_gt, mustang_gt350r, mustang_gt350, sti, ford_gt, ferrari_308, landcruiser, aston_martin, ferrari_250, bmw_m3]
true_values = [45000, 65000, 58000, 32000, 400000, 106500, 40250, 47000, 386000, 41000]

final_score = 0
columns = ['auction_year', 'make', 'model', 'model2', 'model_desc', 'year', 'miles', 'color', 'engine_size', 'cylinders']
test = pd.DataFrame()
for jdx, model in enumerate(model_list):
    for idx, col in enumerate(columns):
        test[col] = pd.Series(model[idx])
    preds = model_pipeline.predict(test)
    final_score += abs(true_values[jdx] - preds)
    print(f'{model[4]} - True value:{true_values[jdx]} | predicted: {preds}')

print(final_score[0]/len(true_values))

gt 6-speed - True value:45000 | predicted: [65876.49]
shelby gt350r - True value:65000 | predicted: [81725.25]
shelby gt350 - True value:58000 | predicted: [72011.76]
impreza sti - True value:32000 | predicted: [25059.607]
gt 1st generation - True value:400000 | predicted: [397575.2]
gtb - True value:106500 | predicted: [85215.99]
cruiser fj45 - True value:40250 | predicted: [36572.703]
martin coupe - True value:47000 | predicted: [40057.43]
250 gte 2+2 series ii - True value:386000 | predicted: [371413.78]
m3 coupe 6-speed - True value:41000 | predicted: [40974.383]
10749.44140625

In [20]:
from sklearn.metrics import mean_squared_error as MSE
# .MSE(X, y)
r2 = hist.score(X, y)
r2_valid = hist.score(X_valid, y_valid)
print(r2, r2_valid)

# MSE = (1 - r2) * np.var(y)
# hist['model']

NameError: name 'X_valid' is not defined

In [21]:
import joblib

# Save the XGB model first:
model_pipeline.named_steps['model'].save_model('./models/xgb_model_01_04_2023.h5')

# Save the preprocessor next
joblib.dump(model_pipeline.named_steps['preprocessor'], './models/preprocessor_01_04_2023.joblib')

# NOT NEEDED ANYMORE
# # This hack allows us to save the sklearn pipeline:
# model_pipeline.named_steps['model'] = None

# # Finally, save the pipeline:
# joblib.dump(model_pipeline, './models/sklearn_pipeline.joblib')

# del model_pipeline

['./models/preprocessor_01_03_2023.joblib']